version: "3.8"

services:
  worker:
    build: .
    environment:
      - APP_MODE=worker
      - KAFKA_BOOTSTRAP_SERVERS=public-meetupmap-kafka-hugh-project.j.aivencloud.com:21116
      - KAFKA_SSL_CA=${KAFKA_SSL_CA}
      - KAFKA_SSL_CERT=${KAFKA_SSL_CERT}
      - KAFKA_SSL_KEY=${KAFKA_SSL_KEY}
      - TOPIC_GROUPS_TO_SCRAPE=groups-to-scrape
      - TOPIC_GROUPS_RAW=groups-raw
      - TOPIC_EVENTS_RAW=events-raw
      - PRO_NETWORKS=pydata
      - MAX_EVENTS_PER_GROUP=50
      - REQUEST_DELAY_SECONDS=1.5
      - PLAYWRIGHT_FALLBACK=true

  sink:
    build: .
    environment:
      - APP_MODE=sink
      - KAFKA_BOOTSTRAP_SERVERS=public-meetupmap-kafka-hugh-project.j.aivencloud.com:21116
      - KAFKA_SSL_CA=${KAFKA_SSL_CA}
      - KAFKA_SSL_CERT=${KAFKA_SSL_CERT}
      - KAFKA_SSL_KEY=${KAFKA_SSL_KEY}
      - POSTGRES_URI=postgres://avnadmin:REDACTED_PASSWORD@public-meetupmap-pg-hugh-project.j.aivencloud.com:21104/defaultdb?sslmode=require
      - TOPIC_GROUPS_RAW=groups-raw
      - TOPIC_EVENTS_RAW=events-raw
