#!/bin/sh
set -e
export LAKEKEEPER__PG_DATABASE_URL_READ="${LAKEKEEPER_PG_URL}"
export LAKEKEEPER__PG_DATABASE_URL_WRITE="${LAKEKEEPER_PG_URL}"
export LAKEKEEPER__PG_ENCRYPTION_KEY="${LAKEKEEPER_PG_ENCRYPTION_KEY}"
export LAKEKEEPER__BASE_URI="${LAKEKEEPER_BASE_URI}"
export LAKEKEEPER__AUTHZ_BACKEND="allowall"
exec /home/nonroot/lakekeeper "$@"
