#!/bin/sh
set -e
echo "DEBUG: LAKEKEEPER_BASE_URI set=${LAKEKEEPER_BASE_URI:+yes} value='${LAKEKEEPER_BASE_URI}'"
echo "DEBUG: LAKEKEEPER_PG_URL set=${LAKEKEEPER_PG_URL:+yes} length=${#LAKEKEEPER_PG_URL}"
echo "DEBUG: LAKEKEEPER_PG_ENCRYPTION_KEY set=${LAKEKEEPER_PG_ENCRYPTION_KEY:+yes} length=${#LAKEKEEPER_PG_ENCRYPTION_KEY}"
export LAKEKEEPER__PG_DATABASE_URL_READ="${LAKEKEEPER_PG_URL}"
export LAKEKEEPER__PG_DATABASE_URL_WRITE="${LAKEKEEPER_PG_URL}"
export LAKEKEEPER__PG_ENCRYPTION_KEY="${LAKEKEEPER_PG_ENCRYPTION_KEY}"
export LAKEKEEPER__BASE_URI="${LAKEKEEPER_BASE_URI}"
export LAKEKEEPER__AUTHZ_BACKEND="allowall"
exec /home/nonroot/lakekeeper "$@"
